# Site settings
title: IITE 动态导航
SEOTitle: 科技前沿 动态导航
header-img: img/home-bg-xg.jpg
email: kcdyx1@hotmail.com
description: "从这里看到世界！"
keyword: "kcdyx1"
url: "http://kcdyx1.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/kcdyx1/kcdyx1.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "尽览全球科技资讯!"
sidebar-avatar: /img/home-qr.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
# weibo_username:     kcdyx1
zhihu_username:     kcdyx1
github_username:    kcdyx1
# facebook_username:  kcdyx1
# jianshu_username:   kcdyx1
# twitter_username:   kcdyx1




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: none
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: kcdyx1

# Gitalk
# gitalk:
#   enable: true    #是否开启Gitalk评论
#   clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#   clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#   repo: kcdyx1.github.io    #仓库名称
#   owner: kcdyx1    #github用户名
#   admin: kcdyx1
#   distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 588940da529435d0d711126d987e6be7

# Google Analytics
ga_track_id: 'UA-124646734-1'            # Format: UA-xxxxxx-xx
ga_domain: auto           # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "全球技术地图",
        href: "http://globaltechmap.com"
    },
    {
        title: "上传网站",
        href: "http://globaltechmap.com/user/login?__refer__=%2Fdocument%2Fedit"
    }
]
